name: Pull Request Automated Checks
on:
  pull_request:
    branches:
      - master
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: yandex-cloud/nodejs-sdk/.github/actions/checkout-and-install-node@8937d1cb6d350912b3e13724b8ae259a1f18a546
      - run: npm ci
  tests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: yandex-cloud/nodejs-sdk/.github/actions/checkout-and-install-node@8937d1cb6d350912b3e13724b8ae259a1f18a546
      - run: npm run test
