name: Pull Request Automated Checks
on:
  pull_request:
    branches:
      - master
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/checkout-and-install-node
      - run: npm ci
  tests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: ./.github/actions/checkout-and-install-node
      - run: npm run test
