name: Pull Request Automated Checks
on:
  pull_request:
    branches:
      - master
      - alpha
      - beta
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: yandex-cloud/nodejs-sdk/.github/actions/checkout-and-install-node@f69248b52b7991214847e889f28ba0883ed0ca2c
      - run: npm run test
  check-endpoints:
    runs-on: ubuntu-20.04
    # Currently, the check-endpoints script fails on the master branch.
    # So we need to continue on error.
    continue-on-error: true
    steps:
      - uses: yandex-cloud/nodejs-sdk/.github/actions/checkout-and-install-node@f69248b52b7991214847e889f28ba0883ed0ca2c
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          git@github.com/
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - run: npm run check-endpoints
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: yandex-cloud/nodejs-sdk/.github/actions/checkout-and-install-node@f69248b52b7991214847e889f28ba0883ed0ca2c
      - run: npm run lint
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: yandex-cloud/nodejs-sdk/.github/actions/checkout-and-install-node@f69248b52b7991214847e889f28ba0883ed0ca2c
      - run: npm run build
